{"f6a5c6c7991a80969fdbcfb3958349c2":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"fc561c39e3b1b4e4","reportUrl":"https://timjden.github.io/cinc_assignment/25//#testresult/fc561c39e3b1b4e4","status":"passed","time":{"start":1667413407999,"stop":1667413413324,"duration":5325}},{"uid":"13e6ea073fed87e7","reportUrl":"https://timjden.github.io/cinc_assignment/24//#testresult/13e6ea073fed87e7","status":"broken","statusDetails":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x555ce63ac2c3 <unknown>\n#1 0x555ce61b583a <unknown>\n#2 0x555ce61ee985 <unknown>\n#3 0x555ce61eeb61 <unknown>\n#4 0x555ce6226d14 <unknown>\n#5 0x555ce620cf6d <unknown>\n#6 0x555ce6224a50 <unknown>\n#7 0x555ce620cd63 <unknown>\n#8 0x555ce61e17e3 <unknown>\n#9 0x555ce61e2a21 <unknown>\n#10 0x555ce63fa18e <unknown>\n#11 0x555ce63fd622 <unknown>\n#12 0x555ce63e0aae <unknown>\n#13 0x555ce63fe2a3 <unknown>\n#14 0x555ce63d4ecf <unknown>\n#15 0x555ce641e588 <unknown>\n#16 0x555ce641e706 <unknown>\n#17 0x555ce64388b2 <unknown>\n#18 0x7fb34a4dc609 <unknown>\n\n","time":{"start":1667412758108,"stop":1667412771913,"duration":13805}},{"uid":"1def942ab23243ef","reportUrl":"https://timjden.github.io/cinc_assignment/23//#testresult/1def942ab23243ef","status":"passed","time":{"start":1667412543528,"stop":1667412548598,"duration":5070}}]},"a34d535ff7756f44d3753d91bfe6b623":{"statistic":{"failed":3,"broken":0,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"357cb1795d771f83","reportUrl":"https://timjden.github.io/cinc_assignment/25//#testresult/357cb1795d771f83","status":"failed","statusDetails":"AssertionError: FAILED SUB-STEP: Given User is on the Home page\nSubstep info: Traceback (most recent call last):\n  File \"steps/login_steps.py\", line 18, in step_impl\n    wait_for_element_visibility(context, page_title_xpath)\n  File \"/home/runner/work/cinc_assignment/cinc_assignment/features/utils.py\", line 5, in wait_for_element_visibility\n    context.wait.until(expected_conditions.visibility_of_element_located((By.XPATH, element_xpath)))\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py\", line 90, in until\n    raise TimeoutException(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x55e01270a2c3 <unknown>\n#1 0x55e01251383a <unknown>\n#2 0x55e01254c985 <unknown>\n#3 0x55e01254cb61 <unknown>\n#4 0x55e012584d14 <unknown>\n#5 0x55e01256af6d <unknown>\n#6 0x55e012582a50 <unknown>\n#7 0x55e01256ad63 <unknown>\n#8 0x55e01253f7e3 <unknown>\n#9 0x55e012540a21 <unknown>\n#10 0x55e01275818e <unknown>\n#11 0x55e01275b622 <unknown>\n#12 0x55e01273eaae <unknown>\n#13 0x55e01275c2a3 <unknown>\n#14 0x55e012732ecf <unknown>\n#15 0x55e01277c588 <unknown>\n#16 0x55e01277c706 <unknown>\n#17 0x55e0127968b2 <unknown>\n#18 0x7f07ef7f3609 <unknown>\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div[1]/div/nav/ul/li[4]/div/ul/li[6]/a\"}\n  (Session info: headless chrome=106.0.5249.119)\nStacktrace:\n#0 0x55e01270a2c3 <unknown>\n#1 0x55e01251383a <unknown>\n#2 0x55e01254c985 <unknown>\n#3 0x55e01254cb61 <unknown>\n#4 0x55e012584d14 <unknown>\n#5 0x55e01256af6d <unknown>\n#6 0x55e012582a50 <unknown>\n#7 0x55e01256ad63 <unknown>\n#8 0x55e01253f7e3 <unknown>\n#9 0x55e012540a21 <unknown>\n#10 0x55e01275818e <unknown>\n#11 0x55e01275b622 <unknown>\n#12 0x55e01273eaae <unknown>\n#13 0x55e01275c2a3 <unknown>\n#14 0x55e012732ecf <unknown>\n#15 0x55e01277c588 <unknown>\n#16 0x55e01277c706 <unknown>\n#17 0x55e0127968b2 <unknown>\n#18 0x7f07ef7f3609 <unknown>\n\n\nTraceback (of failed substep):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n\n","time":{"start":1667413430917,"stop":1667413441282,"duration":10365}},{"uid":"747c1648444e509e","reportUrl":"https://timjden.github.io/cinc_assignment/24//#testresult/747c1648444e509e","status":"failed","statusDetails":"AssertionError\n","time":{"start":1667412789539,"stop":1667412802782,"duration":13243}},{"uid":"d9d6c18078018573","reportUrl":"https://timjden.github.io/cinc_assignment/23//#testresult/d9d6c18078018573","status":"failed","statusDetails":"AssertionError\n","time":{"start":1667412558912,"stop":1667412572022,"duration":13110}}]},"008ee9d2b6280a68e13bf0acd583d8ff":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":1,"unknown":0,"total":3},"items":[{"uid":"f56198b213f587ab","reportUrl":"https://timjden.github.io/cinc_assignment/25//#testresult/f56198b213f587ab","status":"broken","statusDetails":"selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div[1]/div/nav/ul/li[4]/div/ul/li[6]/a\"}\n  (Session info: headless chrome=106.0.5249.119)\nStacktrace:\n#0 0x55e01270a2c3 <unknown>\n#1 0x55e01251383a <unknown>\n#2 0x55e01254c985 <unknown>\n#3 0x55e01254cb61 <unknown>\n#4 0x55e012584d14 <unknown>\n#5 0x55e01256af6d <unknown>\n#6 0x55e012582a50 <unknown>\n#7 0x55e01256ad63 <unknown>\n#8 0x55e01253f7e3 <unknown>\n#9 0x55e012540a21 <unknown>\n#10 0x55e01275818e <unknown>\n#11 0x55e01275b622 <unknown>\n#12 0x55e01273eaae <unknown>\n#13 0x55e01275c2a3 <unknown>\n#14 0x55e012732ecf <unknown>\n#15 0x55e01277c588 <unknown>\n#16 0x55e01277c706 <unknown>\n#17 0x55e0127968b2 <unknown>\n#18 0x7f07ef7f3609 <unknown>\n\n","time":{"start":1667413441283,"stop":1667413451625,"duration":10342}},{"uid":"4da4f61417065692","reportUrl":"https://timjden.github.io/cinc_assignment/24//#testresult/4da4f61417065692","status":"passed","time":{"start":1667412802784,"stop":1667412815768,"duration":12984}},{"uid":"69424292e49dee56","reportUrl":"https://timjden.github.io/cinc_assignment/23//#testresult/69424292e49dee56","status":"broken","statusDetails":"selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div[1]/div/nav/ul/li[4]/div/ul/li[6]/a\"}\n  (Session info: headless chrome=106.0.5249.119)\nStacktrace:\n#0 0x5566378172c3 <unknown>\n#1 0x55663762083a <unknown>\n#2 0x556637659985 <unknown>\n#3 0x556637659b61 <unknown>\n#4 0x556637691d14 <unknown>\n#5 0x556637677f6d <unknown>\n#6 0x55663768fa50 <unknown>\n#7 0x556637677d63 <unknown>\n#8 0x55663764c7e3 <unknown>\n#9 0x55663764da21 <unknown>\n#10 0x55663786518e <unknown>\n#11 0x556637868622 <unknown>\n#12 0x55663784baae <unknown>\n#13 0x5566378692a3 <unknown>\n#14 0x55663783fecf <unknown>\n#15 0x556637889588 <unknown>\n#16 0x556637889706 <unknown>\n#17 0x5566378a38b2 <unknown>\n#18 0x7f93c8083609 <unknown>\n\n","time":{"start":1667412572023,"stop":1667412582321,"duration":10298}}]},"064f3a57ed0026516ddf41142463fedd":{"statistic":{"failed":1,"broken":0,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"cb6b6841bec744cc","reportUrl":"https://timjden.github.io/cinc_assignment/25//#testresult/cb6b6841bec744cc","status":"passed","time":{"start":1667413413324,"stop":1667413430917,"duration":17593}},{"uid":"90bd9f2d78c5f1ac","reportUrl":"https://timjden.github.io/cinc_assignment/24//#testresult/90bd9f2d78c5f1ac","status":"passed","time":{"start":1667412771914,"stop":1667412789538,"duration":17624}},{"uid":"532c3c2e9bcedda9","reportUrl":"https://timjden.github.io/cinc_assignment/23//#testresult/532c3c2e9bcedda9","status":"failed","statusDetails":"AssertionError: FAILED SUB-STEP: Given User is on the Home page\nSubstep info: Traceback (most recent call last):\n  File \"steps/login_steps.py\", line 18, in step_impl\n    wait_for_element_visibility(context, page_title_xpath)\n  File \"/home/runner/work/cinc_assignment/cinc_assignment/features/utils.py\", line 5, in wait_for_element_visibility\n    context.wait.until(expected_conditions.visibility_of_element_located((By.XPATH, element_xpath)))\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py\", line 90, in until\n    raise TimeoutException(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x5566378172c3 <unknown>\n#1 0x55663762083a <unknown>\n#2 0x556637659985 <unknown>\n#3 0x556637659b61 <unknown>\n#4 0x556637691d14 <unknown>\n#5 0x556637677f6d <unknown>\n#6 0x55663768fa50 <unknown>\n#7 0x556637677d63 <unknown>\n#8 0x55663764c7e3 <unknown>\n#9 0x55663764da21 <unknown>\n#10 0x55663786518e <unknown>\n#11 0x556637868622 <unknown>\n#12 0x55663784baae <unknown>\n#13 0x5566378692a3 <unknown>\n#14 0x55663783fecf <unknown>\n#15 0x556637889588 <unknown>\n#16 0x556637889706 <unknown>\n#17 0x5566378a38b2 <unknown>\n#18 0x7f93c8083609 <unknown>\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div[1]/div/nav/ul/li[4]/div/ul/li[6]/a\"}\n  (Session info: headless chrome=106.0.5249.119)\nStacktrace:\n#0 0x5566378172c3 <unknown>\n#1 0x55663762083a <unknown>\n#2 0x556637659985 <unknown>\n#3 0x556637659b61 <unknown>\n#4 0x556637691d14 <unknown>\n#5 0x556637677f6d <unknown>\n#6 0x55663768fa50 <unknown>\n#7 0x556637677d63 <unknown>\n#8 0x55663764c7e3 <unknown>\n#9 0x55663764da21 <unknown>\n#10 0x55663786518e <unknown>\n#11 0x556637868622 <unknown>\n#12 0x55663784baae <unknown>\n#13 0x5566378692a3 <unknown>\n#14 0x55663783fecf <unknown>\n#15 0x556637889588 <unknown>\n#16 0x556637889706 <unknown>\n#17 0x5566378a38b2 <unknown>\n#18 0x7f93c8083609 <unknown>\n\n\nTraceback (of failed substep):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n\n","time":{"start":1667412548599,"stop":1667412558911,"duration":10312}}]}}