{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Product defects","children":[{"name":"AssertionError: FAILED SUB-STEP: Given User is on the Home page\nSubstep info: Traceback (most recent call last):\n  File \"steps/login_steps.py\", line 18, in step_impl\n    wait_for_element_visibility(context, page_title_xpath)\n  File \"/home/runner/work/cinc_assignment/cinc_assignment/features/utils.py\", line 5, in wait_for_element_visibility\n    context.wait.until(expected_conditions.visibility_of_element_located((By.XPATH, element_xpath)))\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py\", line 90, in until\n    raise TimeoutException(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x55e01270a2c3 <unknown>\n#1 0x55e01251383a <unknown>\n#2 0x55e01254c985 <unknown>\n#3 0x55e01254cb61 <unknown>\n#4 0x55e012584d14 <unknown>\n#5 0x55e01256af6d <unknown>\n#6 0x55e012582a50 <unknown>\n#7 0x55e01256ad63 <unknown>\n#8 0x55e01253f7e3 <unknown>\n#9 0x55e012540a21 <unknown>\n#10 0x55e01275818e <unknown>\n#11 0x55e01275b622 <unknown>\n#12 0x55e01273eaae <unknown>\n#13 0x55e01275c2a3 <unknown>\n#14 0x55e012732ecf <unknown>\n#15 0x55e01277c588 <unknown>\n#16 0x55e01277c706 <unknown>\n#17 0x55e0127968b2 <unknown>\n#18 0x7f07ef7f3609 <unknown>\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div[1]/div/nav/ul/li[4]/div/ul/li[6]/a\"}\n  (Session info: headless chrome=106.0.5249.119)\nStacktrace:\n#0 0x55e01270a2c3 <unknown>\n#1 0x55e01251383a <unknown>\n#2 0x55e01254c985 <unknown>\n#3 0x55e01254cb61 <unknown>\n#4 0x55e012584d14 <unknown>\n#5 0x55e01256af6d <unknown>\n#6 0x55e012582a50 <unknown>\n#7 0x55e01256ad63 <unknown>\n#8 0x55e01253f7e3 <unknown>\n#9 0x55e012540a21 <unknown>\n#10 0x55e01275818e <unknown>\n#11 0x55e01275b622 <unknown>\n#12 0x55e01273eaae <unknown>\n#13 0x55e01275c2a3 <unknown>\n#14 0x55e012732ecf <unknown>\n#15 0x55e01277c588 <unknown>\n#16 0x55e01277c706 <unknown>\n#17 0x55e0127968b2 <unknown>\n#18 0x7f07ef7f3609 <unknown>\n\n\nTraceback (of failed substep):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 27, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n\n","children":[{"name":"User can add a Collection with the same name as a deleted Collection -- @1.1 ","uid":"357cb1795d771f83","parentUid":"4dcb2c878254b5a34d1af6b7dd2339e4","status":"failed","time":{"start":1667413430917,"stop":1667413441282,"duration":10365},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":["You already have a collection with that title.","uhqom-duqmum-tepXe7","Test Collection","technical_assignment"]}],"uid":"4dcb2c878254b5a34d1af6b7dd2339e4"}],"uid":"8fb3a91ba5aaf9de24cc8a92edc82b5d"},{"name":"Test defects","children":[{"name":"selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div[1]/div/nav/ul/li[4]/div/ul/li[6]/a\"}\n  (Session info: headless chrome=106.0.5249.119)\nStacktrace:\n#0 0x55e01270a2c3 <unknown>\n#1 0x55e01251383a <unknown>\n#2 0x55e01254c985 <unknown>\n#3 0x55e01254cb61 <unknown>\n#4 0x55e012584d14 <unknown>\n#5 0x55e01256af6d <unknown>\n#6 0x55e012582a50 <unknown>\n#7 0x55e01256ad63 <unknown>\n#8 0x55e01253f7e3 <unknown>\n#9 0x55e012540a21 <unknown>\n#10 0x55e01275818e <unknown>\n#11 0x55e01275b622 <unknown>\n#12 0x55e01273eaae <unknown>\n#13 0x55e01275c2a3 <unknown>\n#14 0x55e012732ecf <unknown>\n#15 0x55e01277c588 <unknown>\n#16 0x55e01277c706 <unknown>\n#17 0x55e0127968b2 <unknown>\n#18 0x7f07ef7f3609 <unknown>\n\n","children":[{"name":"Login -- @1.1 ","uid":"f56198b213f587ab","parentUid":"c4329ca7c68eb2dd15d60b64a77a6df9","status":"broken","time":{"start":1667413441283,"stop":1667413451625,"duration":10342},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":true,"retriesCount":0,"retriesStatusChange":false,"parameters":["uhqom-duqmum-tepXe7","technical_assignment"]}],"uid":"c4329ca7c68eb2dd15d60b64a77a6df9"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}